services:
  db:
    image: pgvector/pgvector:pg16
    container_name: nunchi_db
    environment:
      POSTGRES_USER: park
      POSTGRES_PASSWORD: park
      POSTGRES_DB: nunchi
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  postgres_data: